openapi: 3.0.3
info:
  title: jokes server
servers:
  - url: http://localhost:4444
paths:
  /joke/{id}:
    get:
      summary: повернути жарт по ідентифікатору
    delete:
      summary: видалити
  /joke:
    get:
      summary: отримати випадковий жарт
    post:
      summary: створити новий жарт