openapi: 3.0.3
info:
  title: Jokes Server
  version: 1.0.0
servers:
  - url: http://localhost:4444
paths:
  /joke/{id}:
    get:
      summary: Retrieve a joke by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the joke to retrieve
      responses:
        '200':
          description: A single joke
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Joke'
    delete:
      summary: Delete a joke by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the joke to delete
      responses:
        '204':
          description: Joke deleted successfully
  /jokes:
    get:
      summary: Retrieve a random joke
      responses:
        '200':
          description: An array of jokes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Joke'
    post:
      summary: Create a new joke
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Joke'
      responses:
        '201':
          description: Joke created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Joke'
components:
  schemas:
    Joke:
      type: object
      properties:
        id:
          type: integer
          example: 1
        text:
          type: string
          example: 1+1=11
      required:
        - id
        - text